-- Mark entry as deleted
UPDATE orm_country SET `deleted_at` = "2023-06-06 09:38:10" WHERE  `iso2` ="XZ" AND  `title_de` ="Kosovo";
UPDATE orm_country SET `deleted_at` = "2023-06-06 09:38:10" WHERE  `iso2` ="AN" AND  `title_de` ="Niederländische Antillen";
UPDATE orm_country SET `deleted_at` = "2023-06-06 09:38:10" WHERE  `iso2` ="CS" AND  `title_de` ="Serbien und Montenegro";
UPDATE orm_country SET `deleted_at` = "2023-06-06 09:38:10" WHERE  `iso2` ="MP" AND  `title_de` ="Marhshall Inseln";

-- Sys_ref Delete
UPDATE sys_reference_data SET `is_deleted` = 1 WHERE  `reference_type` ="20" AND  `reference_code` ="XZ";
UPDATE sys_reference_data SET `is_deleted` = 1 WHERE  `reference_type` ="20" AND  `reference_code` ="AN";
UPDATE sys_reference_data SET `is_deleted` = 1 WHERE  `reference_type` ="20" AND  `reference_code` ="CS";
-- NOTE: There were two entries in orm_country with the iso2 code "MP", one of which was misnamed, and the additional line in the deleted statements above corrects that error. There IS an iso2 code "MP" that exists, so it need not be deleted.

-- Insert new entry entries to orm_country
DELETE FROM orm_country WHERE  `iso2` ="AX";
INSERT INTO orm_country SET  `iso2` = "AX",  `iso3` = "ALA",  `title_de` = "Ålandinseln",  `title_en` = "Åland Islands",  `title_fr` = "Åland(les Îles)",  `title_it` = "Isole Åland",  `title_post_sort` = "ALAND ISLAND",  `created_at` = "2023-06-06 09:38:10",  `updated_at` = "2023-06-06 09:38:10";
DELETE FROM orm_country WHERE  `iso2` ="AQ";
INSERT INTO orm_country SET  `iso2` = "AQ", `iso3` = "ATA", `title_de` = "Antarktis", `title_en` = "Antarctica", `title_fr` = "Antarctique", `title_it` = "l Antartida", `title_post_sort` = "ANTARCTICA", `created_at` = "2023-06-06 09:38:10", `updated_at` = "2023-06-06 09:38:10";
DELETE FROM orm_country WHERE  `iso2` ="BQ";
INSERT INTO orm_country SET  `iso2` = "BQ", `iso3` = "BES", `title_de` = "Bonaire, Sint Eustatius u. Saba", `title_en` = "Bonaire, Sint Eustatius and Saba", `title_fr` = "Bonaire, Saint-Eustache et Saba", `title_it` = "Bonaire e Sint Eustatius e Saba", `title_post_sort` = "BONAIR, SINT EUSTATIUS AND SABA", `created_at` = "2023-06-06 09:38:10", `updated_at` = "2023-06-06 09:38:10";
DELETE FROM orm_country WHERE  `iso2` ="BV";
INSERT INTO orm_country SET  `iso2` = "BV", `iso3` = "BVT", `title_de` = "Bouvetinsel", `title_en` = "Bouvet Island", `title_fr` = "Bouvet (l Île)", `title_it` = "Isola Bouvet", `title_post_sort` = "BOUVET ISLAND", `created_at` = "2023-06-06 09:38:10", `updated_at` = "2023-06-06 09:38:10";
DELETE FROM orm_country WHERE  `iso2` ="IO";
INSERT INTO orm_country SET  `iso2` = "IO", `iso3` = "IOT", `title_de` = "Britisches Territorium im Indischen Ozean", `title_en` = "British Indian Ocean Territory (the)", `title_fr` = "Indien (le Territoire britannique de l océan)", `title_it` = "Territorio Britannico dell Oceano Indiano", `title_post_sort` = "BRITISH INDIAN OCEAN TERRITORY", `created_at` = "2023-06-06 09:38:10", `updated_at` = "2023-06-06 09:38:10";
DELETE FROM orm_country WHERE  `iso2` ="CC";
INSERT INTO orm_country SET  `iso2` = "CC", `iso3` = "CCK", `title_de` = "Kokosinseln", `title_en` = "Cocos (Keeling) Islands (the)", `title_fr` = "Cocos (les Îles)/ Keeling (les Îles)", `title_it` = "Isole Cocos", `title_post_sort` = "COCOS ISLAND", `created_at` = "2023-06-06 09:38:10", `updated_at` = "2023-06-06 09:38:10";
DELETE FROM orm_country WHERE  `iso2` ="CW";
INSERT INTO orm_country SET  `iso2` = "CW", `iso3` = "CUW", `title_de` = "Curacao", `title_en` = "Curaçao", `title_fr` = "Curaçao", `title_it` = "Curaçao", `title_post_sort` = "CURACAO", `created_at` = "2023-06-06 09:38:10", `updated_at` = "2023-06-06 09:38:10";
DELETE FROM orm_country WHERE  `iso2` ="TF";
INSERT INTO orm_country SET  `iso2` = "TF", `iso3` = "ATF", `title_de` = "Französischen Süd- und Antarktisgebiete", `title_en` = "French Southern Territories (the)", `title_fr` = "Terres australes françaises", `title_it` = "Terre Australi e Antartiche Francesi", `title_post_sort` = "FRENCH SOUTHERN TERRITORIES", `created_at` = "2023-06-06 09:38:10", `updated_at` = "2023-06-06 09:38:10";
DELETE FROM orm_country WHERE  `iso2` ="HM";
INSERT INTO orm_country SET  `iso2` = "HM", `iso3` = "HMD", `title_de` = "Heard- und McDonald-Inseln", `title_en` = "Heard Island and McDonald Islands", `title_fr` = "Heard-et-Îles MacDonald (l Île)", `title_it` = "Isole Heard e McDonald", `title_post_sort` = "HEARD ISLAND AND MCDONALD ISLANDS", `created_at` = "2023-06-06 09:38:10", `updated_at` = "2023-06-06 09:38:10";
DELETE FROM orm_country WHERE  `iso2` ="MH";
INSERT INTO orm_country SET  `iso2` = "MH", `iso3` = "MHL", `title_de` = "Marshallinseln", `title_en` = "Marshall Islands (the)", `title_fr` = "Marshall (les Îles)", `title_it` = "Isole Marshall", `title_post_sort` = "MARSHALL ISLANDS", `created_at` = "2023-06-06 09:38:10", `updated_at` = "2023-06-06 09:38:10";
DELETE FROM orm_country WHERE  `iso2` ="FM";
INSERT INTO orm_country SET  `iso2` = "FM", `iso3` = "FSM", `title_de` = "Föderierte Staaten von Mikronesien", `title_en` = "Micronesia (Federated States of)", `title_fr` = "Micronésie (États fédérés de)", `title_it` = "Micronesia", `title_post_sort` = "FEDERATED STATES OF MICRONESIA", `created_at` = "2023-06-06 09:38:10", `updated_at` = "2023-06-06 09:38:10";
DELETE FROM orm_country WHERE  `iso2` ="NU";
INSERT INTO orm_country SET  `iso2` = "NU", `iso3` = "NIU", `title_de` = "Niue", `title_en` = "Niue", `title_fr` = "Niue", `title_it` = "Niue", `title_post_sort` = "NIUE", `created_at` = "2023-06-06 09:38:10", `updated_at` = "2023-06-06 09:38:10";
DELETE FROM orm_country WHERE  `iso2` ="BL";
INSERT INTO orm_country SET  `iso2` = "BL", `iso3` = "BLM", `title_de` = "Saint Barthélemy", `title_en` = "Saint Barthélemy", `title_fr` = "Saint-Barthélemy", `title_it` = "Saint-Barthélemy", `title_post_sort` = "SAINT BARTHELEMY", `created_at` = "2023-06-06 09:38:10", `updated_at` = "2023-06-06 09:38:10";
DELETE FROM orm_country WHERE  `iso2` ="MF";
INSERT INTO orm_country SET  `iso2` = "MF", `iso3` = "MAF", `title_de` = "Saint-Martin", `title_en` = "Saint Martin (French part)", `title_fr` = "Saint-Martin (partie française)", `title_it` = "Saint-Martin (Francia)", `title_post_sort` = "SAINT MARTIN", `created_at` = "2023-06-06 09:38:10", `updated_at` = "2023-06-06 09:38:10";
DELETE FROM orm_country WHERE  `iso2` ="SX";
INSERT INTO orm_country SET  `iso2` = "SX", `iso3` = "SXM", `title_de` = "Sint Maarten", `title_en` = "Sint Maarten (Dutch part)", `title_fr` = "Saint-Martin (partie néerlandaise)", `title_it` = "Sint Maarten", `title_post_sort` = "SINT MAARTEN", `created_at` = "2023-06-06 09:38:10", `updated_at` = "2023-06-06 09:38:10";
DELETE FROM orm_country WHERE  `iso2` ="GS";
INSERT INTO orm_country SET  `iso2` = "GS", `iso3` = "SGS", `title_de` = "Süd-Georgien u. südliche Sandwichinseln", `title_en` = "South Georgia and the South Sandwich Islands", `title_fr` = "Géorgie du Sud-et-les Îles Sandwich du Sud", `title_it` = "Georgia del Sud e Isole Sandwich Australi", `title_post_sort` = "SOUTH GEORGIA AND SOUTH SANDWICH ISLANDS", `created_at` = "2023-06-06 09:38:10", `updated_at` = "2023-06-06 09:38:10";
DELETE FROM orm_country WHERE  `iso2` ="SS";
INSERT INTO orm_country SET  `iso2` = "SS", `iso3` = "SSD", `title_de` = "Südsudan", `title_en` = "South Sudan", `title_fr` = "Soudan du Sud", `title_it` = "Sudan del Sud", `title_post_sort` = "SOUTH SUDAN", `created_at` = "2023-06-06 09:38:10", `updated_at` = "2023-06-06 09:38:10";
DELETE FROM orm_country WHERE  `iso2` ="SJ";
INSERT INTO orm_country SET  `iso2` = "SJ", `iso3` = "SJM", `title_de` = "Svalbard u. Jan Mayen", `title_en` = "Svalbard and Jan Mayen", `title_fr` = "Svalbard et l Île Jan Mayen", `title_it` = "Svalbard e Jan Mayen", `title_post_sort` = "SVALBARD AND JAN MAYEN", `created_at` = "2023-06-06 09:38:10", `updated_at` = "2023-06-06 09:38:10";
DELETE FROM orm_country WHERE  `iso2` ="TK";
INSERT INTO orm_country SET  `iso2` = "TK", `iso3` = "TKL", `title_de` = "Tokelau", `title_en` = "Tokelau", `title_fr` = "Tokelau", `title_it` = "Tokelau", `title_post_sort` = "TOKELAU", `created_at` = "2023-06-06 09:38:10", `updated_at` = "2023-06-06 09:38:10";
DELETE FROM orm_country WHERE  `iso2` ="UM";
INSERT INTO orm_country SET  `iso2` = "UM", `iso3` = "UMI", `title_de` = "Kleinere abgelegene Inseln der Vereinigten Staaten", `title_en` = "United States Minor Outlying Islands (the)", `title_fr` = "Îles mineures éloignées des États-Unis", `title_it` = "Isole Minori Esterne degli Stati Uniti d America", `title_post_sort` = "UNITED STATES MINOR OUTLYING ISLANDS", `created_at` = "2023-06-06 09:38:10", `updated_at` = "2023-06-06 09:38:10";
DELETE FROM orm_country WHERE  `iso2` ="EH";
INSERT INTO orm_country SET  `iso2` = "EH", `iso3` = "ESH", `title_de` = "Westsahara", `title_en` = "Western Sahara", `title_fr` = "Sahara occidental *", `title_it` = "Sahara Occidentale", `title_post_sort` = "WESTERN SAHARA", `created_at` = "2023-06-06 09:38:10", `updated_at` = "2023-06-06 09:38:10";


-- SYS_REFERENCE_DATA NEW
DELETE FROM sys_reference_data WHERE  `reference_type` ="20" AND  `reference_code` ="AX";
INSERT INTO sys_reference_data SET  `reference_code` = "AX",  `text_g` = "Ålandinseln",  `text_e` = "Åland Islands",  `text_f` = "Åland(les Îles)",  `text_i` = "Isole Åland";
DELETE FROM sys_reference_data WHERE  `reference_type` ="20" AND  `reference_code` ="AQ";
INSERT INTO sys_reference_data SET  `reference_code` = "AQ", `text_g` = "Antarktis", `text_e` = "Antarctica", `text_f` = "Antarctique", `text_i` = "l Antartida";
DELETE FROM sys_reference_data WHERE  `reference_type` ="20" AND  `reference_code` ="BQ";
INSERT INTO sys_reference_data SET  `reference_code` = "BQ", `text_g` = "Bonaire, Sint Eustatius u. Saba", `text_e` = "Bonaire, Sint Eustatius and Saba", `text_f` = "Bonaire, Saint-Eustache et Saba", `text_i` = "Bonaire e Sint Eustatius e Saba";
DELETE FROM sys_reference_data WHERE  `reference_type` ="20" AND  `reference_code` ="BV";
INSERT INTO sys_reference_data SET  `reference_code` = "BV", `text_g` = "Bouvetinsel", `text_e` = "Bouvet Island", `text_f` = "Bouvet (l Île)", `text_i` = "Isola Bouvet";
DELETE FROM sys_reference_data WHERE  `reference_type` ="20" AND  `reference_code` ="IO";
INSERT INTO sys_reference_data SET  `reference_code` = "IO", `text_g` = "Britisches Territorium im Indischen Ozean", `text_e` = "British Indian Ocean Territory (the)", `text_f` = "Indien (le Territoire britannique de l océan)", `text_i` = "Territorio Britannico dell Oceano Indiano";
DELETE FROM sys_reference_data WHERE  `reference_type` ="20" AND  `reference_code` ="CC";
INSERT INTO sys_reference_data SET  `reference_code` = "CC", `text_g` = "Kokosinseln", `text_e` = "Cocos (Keeling) Islands (the)", `text_f` = "Cocos (les Îles)/ Keeling (les Îles)", `text_i` = "Isole Cocos";
DELETE FROM sys_reference_data WHERE  `reference_type` ="20" AND  `reference_code` ="CW";
INSERT INTO sys_reference_data SET  `reference_code` = "CW", `text_g` = "Curacao", `text_e` = "Curaçao", `text_f` = "Curaçao", `text_i` = "Curaçao";
DELETE FROM sys_reference_data WHERE  `reference_type` ="20" AND  `reference_code` ="TF";
INSERT INTO sys_reference_data SET  `reference_code` = "TF", `text_g` = "Französischen Süd- und Antarktisgebiete", `text_e` = "French Southern Territories (the)", `text_f` = "Terres australes françaises", `text_i` = "Terre Australi e Antartiche Francesi";
DELETE FROM sys_reference_data WHERE  `reference_type` ="20" AND  `reference_code` ="HM";
INSERT INTO sys_reference_data SET  `reference_code` = "HM", `text_g` = "Heard- und McDonald-Inseln", `text_e` = "Heard Island and McDonald Islands", `text_f` = "Heard-et-Îles MacDonald (l Île)", `text_i` = "Isole Heard e McDonald";
DELETE FROM sys_reference_data WHERE  `reference_type` ="20" AND  `reference_code` ="MH";
INSERT INTO sys_reference_data SET  `reference_code` = "MH", `text_g` = "Marshallinseln", `text_e` = "Marshall Islands (the)", `text_f` = "Marshall (les Îles)", `text_i` = "Isole Marshall";
DELETE FROM sys_reference_data WHERE  `reference_type` ="20" AND  `reference_code` ="FM";
INSERT INTO sys_reference_data SET  `reference_code` = "FM", `text_g` = "Föderierte Staaten von Mikronesien", `text_e` = "Micronesia (Federated States of)", `text_f` = "Micronésie (États fédérés de)", `text_i` = "Micronesia";
DELETE FROM sys_reference_data WHERE  `reference_type` ="20" AND  `reference_code` ="NU";
INSERT INTO sys_reference_data SET  `reference_code` = "NU", `text_g` = "Niue", `text_e` = "Niue", `text_f` = "Niue", `text_i` = "Niue";
DELETE FROM sys_reference_data WHERE  `reference_type` ="20" AND  `reference_code` ="BL";
INSERT INTO sys_reference_data SET  `reference_code` = "BL", `text_g` = "Saint Barthélemy", `text_e` = "Saint Barthélemy", `text_f` = "Saint-Barthélemy", `text_i` = "Saint-Barthélemy";
DELETE FROM sys_reference_data WHERE  `reference_type` ="20" AND  `reference_code` ="MF";
INSERT INTO sys_reference_data SET  `reference_code` = "MF", `text_g` = "Saint-Martin", `text_e` = "Saint Martin (French part)", `text_f` = "Saint-Martin (partie française)", `text_i` = "Saint-Martin (Francia)";
DELETE FROM sys_reference_data WHERE  `reference_type` ="20" AND  `reference_code` ="SX";
INSERT INTO sys_reference_data SET  `reference_code` = "SX", `text_g` = "Sint Maarten", `text_e` = "Sint Maarten (Dutch part)", `text_f` = "Saint-Martin (partie néerlandaise)", `text_i` = "Sint Maarten";
DELETE FROM sys_reference_data WHERE  `reference_type` ="20" AND  `reference_code` ="GS";
INSERT INTO sys_reference_data SET  `reference_code` = "GS", `text_g` = "Süd-Georgien u. südliche Sandwichinseln", `text_e` = "South Georgia and the South Sandwich Islands", `text_f` = "Géorgie du Sud-et-les Îles Sandwich du Sud", `text_i` = "Georgia del Sud e Isole Sandwich Australi";
DELETE FROM sys_reference_data WHERE  `reference_type` ="20" AND  `reference_code` ="SS";
INSERT INTO sys_reference_data SET  `reference_code` = "SS", `text_g` = "Südsudan", `text_e` = "South Sudan", `text_f` = "Soudan du Sud", `text_i` = "Sudan del Sud";
DELETE FROM sys_reference_data WHERE  `reference_type` ="20" AND  `reference_code` ="SJ";
INSERT INTO sys_reference_data SET  `reference_code` = "SJ", `text_g` = "Svalbard u. Jan Mayen", `text_e` = "Svalbard and Jan Mayen", `text_f` = "Svalbard et l Île Jan Mayen", `text_i` = "Svalbard e Jan Mayen";
DELETE FROM sys_reference_data WHERE  `reference_type` ="20" AND  `reference_code` ="TK";
INSERT INTO sys_reference_data SET  `reference_code` = "TK", `text_g` = "Tokelau", `text_e` = "Tokelau", `text_f` = "Tokelau", `text_i` = "Tokelau";
DELETE FROM sys_reference_data WHERE  `reference_type` ="20" AND  `reference_code` ="UM";
INSERT INTO sys_reference_data SET  `reference_code` = "UM", `text_g` = "Kleinere abgelegene Inseln der Vereinigten Staaten", `text_e` = "United States Minor Outlying Islands (the)", `text_f` = "Îles mineures éloignées des États-Unis", `text_i` = "Isole Minori Esterne degli Stati Uniti d America";
DELETE FROM sys_reference_data WHERE  `reference_type` ="20" AND  `reference_code` ="EH";
INSERT INTO sys_reference_data SET  `reference_code` = "EH", `text_g` = "Westsahara", `text_e` = "Western Sahara", `text_f` = "Sahara occidental *", `text_i` = "Sahara Occidentale";


-- Update DE name, iso3 and post_sort
UPDATE orm_country SET  `iso3` ="ASM",  `title_de` ="Amerikanisch-Samoa",  `title_post_sort` ="AMERICAN SAMOA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="AS";
UPDATE orm_country SET  `iso3` ="BIH",  `title_de` ="Bosnien u. Herzegowina",  `title_post_sort` ="BOSNIA-HERZEGOVINA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="BA";
UPDATE orm_country SET  `iso3` ="BWA",  `title_de` ="Botsuana",  `title_post_sort` ="BOTSWANA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="BW";
UPDATE orm_country SET  `iso3` ="CAF",  `title_de` ="Zentralafrikanische Republik",  `title_post_sort` ="CENTRAL AFRICAN REPUBLIC",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="CF";
UPDATE orm_country SET  `iso3` ="CHN",  `title_de` ="China",  `title_post_sort` ="CHINA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="CN";
UPDATE orm_country SET  `iso3` ="COG",  `title_de` ="Kongo-Brazzavilled",  `title_post_sort` ="THE CONGO",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="CG";
UPDATE orm_country SET  `iso3` ="COK",  `title_de` ="Cookinseln",  `title_post_sort` ="COOK ISLANDS",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="CK";
UPDATE orm_country SET  `iso3` ="CIV",  `title_de` ="Elfenbeinküste",  `title_post_sort` ="COTE D IVOIRE",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="CI";
UPDATE orm_country SET  `iso3` ="DJI",  `title_de` ="Dschibuti",  `title_post_sort` ="DJIBOUTI",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="DJ";
UPDATE orm_country SET  `iso3` ="SWZ",  `title_de` ="Eswatini",  `title_post_sort` ="ESTWATINI",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="SZ";
UPDATE orm_country SET  `iso3` ="GIN",  `title_de` ="Guinea",  `title_post_sort` ="GUINEA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="GN";
UPDATE orm_country SET  `iso3` ="NFK",  `title_de` ="Norfolkinsel",  `title_post_sort` ="NORFOLK ISLAND",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="NF";
UPDATE orm_country SET  `iso3` ="MKD",  `title_de` ="Nordmazedonien",  `title_post_sort` ="NORTH MACEDONIA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="MK";
UPDATE orm_country SET  `iso3` ="SHN",  `title_de` ="Helena, Ascension und Tristan da Cunha",  `title_post_sort` ="SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="SH";
UPDATE orm_country SET  `iso3` ="KNA",  `title_de` ="Sankt Christopher und Nevis",  `title_post_sort` ="SAINT KITTS AND NEVIS",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="KN";
UPDATE orm_country SET  `iso3` ="WSM",  `title_de` ="Samoa",  `title_post_sort` ="SAMOA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="WS";
UPDATE orm_country SET  `iso3` ="ARE",  `title_de` ="Vereinigte Arabische Emirate",  `title_post_sort` ="UNITED ARAB EMIRATES",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="AE";
UPDATE orm_country SET  `iso3` ="GBR",  `title_de` ="Vereinigtes Königreich (Großbritannien, England)",  `title_post_sort` ="UNITED KINGDOM",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="GB";

-- Update iso3 and post_sort
UPDATE orm_country SET  `iso3` ="AFG",  `title_post_sort` ="AFGHANISTAN",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="AF";
UPDATE orm_country SET  `iso3` ="ALB",  `title_post_sort` ="ALBANIA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="AL";
UPDATE orm_country SET  `iso3` ="DZA",  `title_post_sort` ="ALGERIA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="DZ";
UPDATE orm_country SET  `iso3` ="VIR",  `title_post_sort` ="AMERICAN VIRGIN ISLANDS",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="VI";
UPDATE orm_country SET  `iso3` ="AND",  `title_post_sort` ="ANDORRA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="AD";
UPDATE orm_country SET  `iso3` ="AGO",  `title_post_sort` ="ANGOLA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="AO";
UPDATE orm_country SET  `iso3` ="AIA",  `title_post_sort` ="ANGUILLA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="AI";
UPDATE orm_country SET  `iso3` ="ATG",  `title_post_sort` ="ANTIGUA AND BARBUDA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="AG";
UPDATE orm_country SET  `iso3` ="ARG",  `title_post_sort` ="ARGENTINA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="AR";
UPDATE orm_country SET  `iso3` ="ARM",  `title_post_sort` ="ARMENIA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="AM";
UPDATE orm_country SET  `iso3` ="ABW",  `title_post_sort` ="ARUBA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="AW";
UPDATE orm_country SET  `iso3` ="AUS",  `title_post_sort` ="AUSTRALIA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="AU";
UPDATE orm_country SET  `iso3` ="AZE",  `title_post_sort` ="AZERBAIJAN",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="AZ";
UPDATE orm_country SET  `iso3` ="BHS",  `title_post_sort` ="BAHAMAS",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="BS";
UPDATE orm_country SET  `iso3` ="BHR",  `title_post_sort` ="BAHRAIN",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="BH";
UPDATE orm_country SET  `iso3` ="BGD",  `title_post_sort` ="BANGLADESH",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="BD";
UPDATE orm_country SET  `iso3` ="BRB",  `title_post_sort` ="BARBADOS",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="BB";
UPDATE orm_country SET  `iso3` ="BLR",  `title_post_sort` ="BELARUS",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="BY";
UPDATE orm_country SET  `iso3` ="BLZ",  `title_post_sort` ="BELIZE",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="BZ";
UPDATE orm_country SET  `iso3` ="BEN",  `title_post_sort` ="BENIN",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="BJ";
UPDATE orm_country SET  `iso3` ="BMU",  `title_post_sort` ="BERMUDA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="BM";
UPDATE orm_country SET  `iso3` ="BTN",  `title_post_sort` ="BHUTAN",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="BT";
UPDATE orm_country SET  `iso3` ="BOL",  `title_post_sort` ="BOLIVIA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="BO";
UPDATE orm_country SET  `iso3` ="BRA",  `title_post_sort` ="BRAZIL",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="BR";
UPDATE orm_country SET  `iso3` ="BRN",  `title_post_sort` ="BRUNEI DARUSSALAM",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="BN";
UPDATE orm_country SET  `iso3` ="BFA",  `title_post_sort` ="BURKINA FASO",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="BF";
UPDATE orm_country SET  `iso3` ="BDI",  `title_post_sort` ="BURUNDI",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="BI";
UPDATE orm_country SET  `iso3` ="CPV",  `title_post_sort` ="CAPE VERDE",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="CV";
UPDATE orm_country SET  `iso3` ="KHM",  `title_post_sort` ="CAMBODIA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="KH";
UPDATE orm_country SET  `iso3` ="CMR",  `title_post_sort` ="CAMEROON",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="CM";
UPDATE orm_country SET  `iso3` ="CAN",  `title_post_sort` ="CANADA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="CA";
UPDATE orm_country SET  `iso3` ="CYM",  `title_post_sort` ="CAYMAN ISLANDS",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="KY";
UPDATE orm_country SET  `iso3` ="TCD",  `title_post_sort` ="CHAD",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="TD";
UPDATE orm_country SET  `iso3` ="CHL",  `title_post_sort` ="CHILE",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="CL";
UPDATE orm_country SET  `iso3` ="CXR",  `title_post_sort` ="CHRISTMAS ISLAND",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="CX";
UPDATE orm_country SET  `iso3` ="COL",  `title_post_sort` ="COLOMBIA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="CO";
UPDATE orm_country SET  `iso3` ="COM",  `title_post_sort` ="COMOROS",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="KM";
UPDATE orm_country SET  `iso3` ="COD",  `title_post_sort` ="DEM REP OF THE CONGO",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="CD";
UPDATE orm_country SET  `iso3` ="CRI",  `title_post_sort` ="COSTA RICA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="CR";
UPDATE orm_country SET  `iso3` ="CUB",  `title_post_sort` ="CUBA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="CU";
UPDATE orm_country SET  `iso3` ="DMA",  `title_post_sort` ="DOMINICA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="DM";
UPDATE orm_country SET  `iso3` ="DOM",  `title_post_sort` ="DOMINICAN REPUBLIC",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="DO";
UPDATE orm_country SET  `iso3` ="ECU",  `title_post_sort` ="ECUADOR",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="EC";
UPDATE orm_country SET  `iso3` ="EGY",  `title_post_sort` ="EGYPT",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="EG";
UPDATE orm_country SET  `iso3` ="SLV",  `title_post_sort` ="EL SALVADOR",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="SV";
UPDATE orm_country SET  `iso3` ="GNQ",  `title_post_sort` ="EQUATORIAL GUINEA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="GQ";
UPDATE orm_country SET  `iso3` ="ERI",  `title_post_sort` ="ERITREA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="ER";
UPDATE orm_country SET  `iso3` ="ETH",  `title_post_sort` ="ETHIOPIA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="ET";
UPDATE orm_country SET  `iso3` ="FLK",  `title_post_sort` ="FALKLAND ISLANDS",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="FK";
UPDATE orm_country SET  `iso3` ="FRO",  `title_post_sort` ="FAROE ISLANDS",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="FO";
UPDATE orm_country SET  `iso3` ="FJI",  `title_post_sort` ="FIJI",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="FJ";
UPDATE orm_country SET  `iso3` ="GUF",  `title_post_sort` ="FRENCH GUIANA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="GF";
UPDATE orm_country SET  `iso3` ="PYF",  `title_post_sort` ="FRENCH POLYNESIA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="PF";
UPDATE orm_country SET  `iso3` ="GAB",  `title_post_sort` ="GABON",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="GA";
UPDATE orm_country SET  `iso3` ="GMB",  `title_post_sort` ="GAMBIA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="GM";
UPDATE orm_country SET  `iso3` ="GEO",  `title_post_sort` ="GEORGIA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="GE";
UPDATE orm_country SET  `iso3` ="GHA",  `title_post_sort` ="GHANA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="GH";
UPDATE orm_country SET  `iso3` ="GIB",  `title_post_sort` ="GIBRALTAR",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="GI";
UPDATE orm_country SET  `iso3` ="GRL",  `title_post_sort` ="GREENLAND",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="GL";
UPDATE orm_country SET  `iso3` ="GRD",  `title_post_sort` ="GRENADA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="GD";
UPDATE orm_country SET  `iso3` ="GLP",  `title_post_sort` ="GUADELOUPE",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="GP";
UPDATE orm_country SET  `iso3` ="GUM",  `title_post_sort` ="GUAM",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="GU";
UPDATE orm_country SET  `iso3` ="GTM",  `title_post_sort` ="GUATEMALA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="GT";
UPDATE orm_country SET  `iso3` ="GGY",  `title_post_sort` ="GUERNSEY",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="GG";
UPDATE orm_country SET  `iso3` ="GNB",  `title_post_sort` ="GUINEA-BISSAU",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="GW";
UPDATE orm_country SET  `iso3` ="GUY",  `title_post_sort` ="GUYANA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="GY";
UPDATE orm_country SET  `iso3` ="HTI",  `title_post_sort` ="HAITI",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="HT";
UPDATE orm_country SET  `iso3` ="HND",  `title_post_sort` ="HONDURAS",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="HN";
UPDATE orm_country SET  `iso3` ="HKG",  `title_post_sort` ="HONG KONG",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="HK";
UPDATE orm_country SET  `iso3` ="ISL",  `title_post_sort` ="ICELAND",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="IS";
UPDATE orm_country SET  `iso3` ="IND",  `title_post_sort` ="INDIA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="IN";
UPDATE orm_country SET  `iso3` ="IDN",  `title_post_sort` ="INDONESIA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="ID";
UPDATE orm_country SET  `iso3` ="IRN",  `title_post_sort` ="IRAN",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="IR";
UPDATE orm_country SET  `iso3` ="IRQ",  `title_post_sort` ="IRAQ",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="IQ";
UPDATE orm_country SET  `iso3` ="IMN",  `title_post_sort` ="ISLE OF MAN",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="IM";
UPDATE orm_country SET  `iso3` ="ISR",  `title_post_sort` ="ISRAEL",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="IL";
UPDATE orm_country SET  `iso3` ="JAM",  `title_post_sort` ="JAMAICA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="JM";
UPDATE orm_country SET  `iso3` ="JPN",  `title_post_sort` ="JAPAN",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="JP";
UPDATE orm_country SET  `iso3` ="JEY",  `title_post_sort` ="JERSEY",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="JE";
UPDATE orm_country SET  `iso3` ="JOR",  `title_post_sort` ="JORDAN",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="JO";
UPDATE orm_country SET  `iso3` ="KAZ",  `title_post_sort` ="KAZAKSTAN",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="KZ";
UPDATE orm_country SET  `iso3` ="KEN",  `title_post_sort` ="KENYA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="KE";
UPDATE orm_country SET  `iso3` ="KIR",  `title_post_sort` ="KIRIBATI",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="KI";
UPDATE orm_country SET  `iso3` ="PRK",  `title_post_sort` ="KOREA, DEMOCRATIC PEOPLE S REPUBLIC OF",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="KP";
UPDATE orm_country SET  `iso3` ="KOR",  `title_post_sort` ="KOREA, REPUBLIC OF",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="KR";
UPDATE orm_country SET  `iso3` ="KWT",  `title_post_sort` ="KUWAIT",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="KW";
UPDATE orm_country SET  `iso3` ="KGZ",  `title_post_sort` ="KYRGYZSTAN",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="KG";
UPDATE orm_country SET  `iso3` ="LAO",  `title_post_sort` ="LAO PEOPLE S DEMOCRATIC REPUBLIC",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="LA";
UPDATE orm_country SET  `iso3` ="LBN",  `title_post_sort` ="LEBANON",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="LB";
UPDATE orm_country SET  `iso3` ="LSO",  `title_post_sort` ="LESOTHO",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="LS";
UPDATE orm_country SET  `iso3` ="LBR",  `title_post_sort` ="LIBERIA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="LR";
UPDATE orm_country SET  `iso3` ="LBY",  `title_post_sort` ="LIBYAN",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="LY";
UPDATE orm_country SET  `iso3` ="LIE",  `title_post_sort` ="LIECHTENSTEIN",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="LI";
UPDATE orm_country SET  `iso3` ="MAC",  `title_post_sort` ="MACAO",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="MO";
UPDATE orm_country SET  `iso3` ="MDG",  `title_post_sort` ="MADAGASCAR",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="MG";
UPDATE orm_country SET  `iso3` ="MWI",  `title_post_sort` ="MALAWI",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="MW";
UPDATE orm_country SET  `iso3` ="MYS",  `title_post_sort` ="MALAYSIA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="MY";
UPDATE orm_country SET  `iso3` ="MDV",  `title_post_sort` ="MALDIVES",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="MV";
UPDATE orm_country SET  `iso3` ="MLI",  `title_post_sort` ="MALI",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="ML";
UPDATE orm_country SET  `iso3` ="MTQ",  `title_post_sort` ="MARTINIQUE",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="MQ";
UPDATE orm_country SET  `iso3` ="MRT",  `title_post_sort` ="MAURITANIA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="MR";
UPDATE orm_country SET  `iso3` ="MUS",  `title_post_sort` ="MAURITIUS",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="MU";
UPDATE orm_country SET  `iso3` ="MYT",  `title_post_sort` ="MAYOTTE",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="YT";
UPDATE orm_country SET  `iso3` ="MEX",  `title_post_sort` ="MEXICO",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="MX";
UPDATE orm_country SET  `iso3` ="MDA",  `title_post_sort` ="MOLDOVA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="MD";
UPDATE orm_country SET  `iso3` ="MCO",  `title_post_sort` ="MONACO",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="MC";
UPDATE orm_country SET  `iso3` ="MNG",  `title_post_sort` ="MONGOLIA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="MN";
UPDATE orm_country SET  `iso3` ="MNE",  `title_post_sort` ="MONTENEGRO",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="ME";
UPDATE orm_country SET  `iso3` ="MSR",  `title_post_sort` ="MONTSERRAT",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="MS";
UPDATE orm_country SET  `iso3` ="MAR",  `title_post_sort` ="MOROCCO",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="MA";
UPDATE orm_country SET  `iso3` ="MOZ",  `title_post_sort` ="MOZAMBIQUE",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="MZ";
UPDATE orm_country SET  `iso3` ="MMR",  `title_post_sort` ="MYANMAR",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="MM";
UPDATE orm_country SET  `iso3` ="NAM",  `title_post_sort` ="NAMIBIA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="NA";
UPDATE orm_country SET  `iso3` ="NRU",  `title_post_sort` ="NAURU",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="NR";
UPDATE orm_country SET  `iso3` ="NPL",  `title_post_sort` ="NEPAL",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="NP";
UPDATE orm_country SET  `iso3` ="NCL",  `title_post_sort` ="NEW CALEDONIA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="NC";
UPDATE orm_country SET  `iso3` ="NZL",  `title_post_sort` ="NEW ZEALAND",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="NZ";
UPDATE orm_country SET  `iso3` ="NIC",  `title_post_sort` ="NICARAGUA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="NI";
UPDATE orm_country SET  `iso3` ="NER",  `title_post_sort` ="NIGER",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="NE";
UPDATE orm_country SET  `iso3` ="NGA",  `title_post_sort` ="NIGERIA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="NG";
UPDATE orm_country SET  `iso3` ="MNP",  `title_post_sort` ="NORTHERN MARIANA ISLANDS",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="MP";
UPDATE orm_country SET  `iso3` ="NOR",  `title_post_sort` ="NORWAY",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="NO";
UPDATE orm_country SET  `iso3` ="OMN",  `title_post_sort` ="OMAN",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="OM";
UPDATE orm_country SET  `iso3` ="PAK",  `title_post_sort` ="PAKISTAN",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="PK";
UPDATE orm_country SET  `iso3` ="PLW",  `title_post_sort` ="PALAU",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="PW";
UPDATE orm_country SET  `iso3` ="PSE",  `title_post_sort` ="PALESTINE",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="PS";
UPDATE orm_country SET  `iso3` ="PAN",  `title_post_sort` ="PANAMA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="PA";
UPDATE orm_country SET  `iso3` ="PNG",  `title_post_sort` ="PAPUA NEW GUINEA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="PG";
UPDATE orm_country SET  `iso3` ="PRY",  `title_post_sort` ="PARAGUAY",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="PY";
UPDATE orm_country SET  `iso3` ="PER",  `title_post_sort` ="PERU",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="PE";
UPDATE orm_country SET  `iso3` ="PHL",  `title_post_sort` ="PHILIPPINES",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="PH";
UPDATE orm_country SET  `iso3` ="PCN",  `title_post_sort` ="PITCAIRN",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="PN";
UPDATE orm_country SET  `iso3` ="PRI",  `title_post_sort` ="PUERTO RICO",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="PR";
UPDATE orm_country SET  `iso3` ="QAT",  `title_post_sort` ="QATAR",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="QA";
UPDATE orm_country SET  `iso3` ="REU",  `title_post_sort` ="REUNION",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="RE";
UPDATE orm_country SET  `iso3` ="RUS",  `title_post_sort` ="RUSSIAN FEDERATION",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="RU";
UPDATE orm_country SET  `iso3` ="RWA",  `title_post_sort` ="RWANDA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="RW";
UPDATE orm_country SET  `iso3` ="LCA",  `title_post_sort` ="SAINT LUCIA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="LC";
UPDATE orm_country SET  `iso3` ="SPM",  `title_post_sort` ="SAINT PIERRE AND MIQUELON",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="PM";
UPDATE orm_country SET  `iso3` ="VCT",  `title_post_sort` ="SAINT VINCENT AND THE GRENADINES",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="VC";
UPDATE orm_country SET  `iso3` ="SMR",  `title_post_sort` ="SAN MARINO",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="SM";
UPDATE orm_country SET  `iso3` ="STP",  `title_post_sort` ="SAO TOME AND PRINCIPE",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="ST";
UPDATE orm_country SET  `iso3` ="SAU",  `title_post_sort` ="SAUDI ARABIA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="SA";
UPDATE orm_country SET  `iso3` ="SEN",  `title_post_sort` ="SENEGAL",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="SN";
UPDATE orm_country SET  `iso3` ="SRB",  `title_post_sort` ="SERBIA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="RS";
UPDATE orm_country SET  `iso3` ="SYC",  `title_post_sort` ="SEYCHELLES",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="SC";
UPDATE orm_country SET  `iso3` ="SLE",  `title_post_sort` ="SIERRA LEONE",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="SL";
UPDATE orm_country SET  `iso3` ="SGP",  `title_post_sort` ="SINGAPORE",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="SG";
UPDATE orm_country SET  `iso3` ="SLB",  `title_post_sort` ="SOLOMON ISLANDS",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="SB";
UPDATE orm_country SET  `iso3` ="SOM",  `title_post_sort` ="SOMALIA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="SO";
UPDATE orm_country SET  `iso3` ="ZAF",  `title_post_sort` ="SOUTH AFRICA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="ZA";
UPDATE orm_country SET  `iso3` ="LKA",  `title_post_sort` ="SRI LANKA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="LK";
UPDATE orm_country SET  `iso3` ="SDN",  `title_post_sort` ="SUDAN",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="SD";
UPDATE orm_country SET  `iso3` ="SUR",  `title_post_sort` ="SURINAME",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="SR";
UPDATE orm_country SET  `iso3` ="CHE",  `title_post_sort` ="SCHWEIZ",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="CH";
UPDATE orm_country SET  `iso3` ="SYR",  `title_post_sort` ="SYRIAN ARAB REPUBLIC",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="SY";
UPDATE orm_country SET  `iso3` ="TWN",  `title_post_sort` ="CHINA, TAIWAN",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="TW";
UPDATE orm_country SET  `iso3` ="TJK",  `title_post_sort` ="TAJIKISTAN",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="TJ";
UPDATE orm_country SET  `iso3` ="TZA",  `title_post_sort` ="TANZANIA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="TZ";
UPDATE orm_country SET  `iso3` ="THA",  `title_post_sort` ="THAILAND",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="TH";
UPDATE orm_country SET  `iso3` ="TLS",  `title_post_sort` ="TIMOR LESTE",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="TL";
UPDATE orm_country SET  `iso3` ="TGO",  `title_post_sort` ="TOGO",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="TG";
UPDATE orm_country SET  `iso3` ="TON",  `title_post_sort` ="TONGA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="TO";
UPDATE orm_country SET  `iso3` ="TTO",  `title_post_sort` ="TRINIDAD AND TOBAGO",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="TT";
UPDATE orm_country SET  `iso3` ="TUN",  `title_post_sort` ="TUNISIA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="TN";
UPDATE orm_country SET  `iso3` ="TUR",  `title_post_sort` ="TURKEY",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="TR";
UPDATE orm_country SET  `iso3` ="TKM",  `title_post_sort` ="TURKMENISTAN",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="TM";
UPDATE orm_country SET  `iso3` ="TUV",  `title_post_sort` ="TUVALU",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="TV";
UPDATE orm_country SET  `iso3` ="UGA",  `title_post_sort` ="UGANDA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="UG";
UPDATE orm_country SET  `iso3` ="UKR",  `title_post_sort` ="UKRAINE",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="UA";
UPDATE orm_country SET  `iso3` ="USA",  `title_post_sort` ="UNITED STATES",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="US";
UPDATE orm_country SET  `iso3` ="URY",  `title_post_sort` ="URUGUAY",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="UY";
UPDATE orm_country SET  `iso3` ="UZB",  `title_post_sort` ="UZBEKISTAN",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="UZ";
UPDATE orm_country SET  `iso3` ="VUT",  `title_post_sort` ="VANUATU",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="VU";
UPDATE orm_country SET  `iso3` ="VAT",  `title_post_sort` ="VATICAN CITY STATE",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="VA";
UPDATE orm_country SET  `iso3` ="VEN",  `title_post_sort` ="VENEZUELA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="VE";
UPDATE orm_country SET  `iso3` ="VNM",  `title_post_sort` ="VIETNAM",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="VN";
UPDATE orm_country SET  `iso3` ="VGB",  `title_post_sort` ="BRITISH VIRGIN ISLANDS",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="VG";
UPDATE orm_country SET  `iso3` ="WLF",  `title_post_sort` ="WALLIS AND FUTUNA ISLANDS",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="WF";
UPDATE orm_country SET  `iso3` ="YEM",  `title_post_sort` ="YEMEN",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="YE";
UPDATE orm_country SET  `iso3` ="ZMB",  `title_post_sort` ="ZAMBIA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="ZM";
UPDATE orm_country SET  `iso3` ="ZWE",  `title_post_sort` ="ZIMBABWE",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="ZW";
UPDATE orm_country SET  `iso3` ="AUT",  `title_post_sort` ="OESTERREICH",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="AT";
UPDATE orm_country SET  `iso3` ="BEL",  `title_post_sort` ="BELGIUM",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="BE";
UPDATE orm_country SET  `iso3` ="BGR",  `title_post_sort` ="BULGARIA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="BG";
UPDATE orm_country SET  `iso3` ="HRV",  `title_post_sort` ="CROATIA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="HR";
UPDATE orm_country SET  `iso3` ="CYP",  `title_post_sort` ="CYPRUS",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="CY";
UPDATE orm_country SET  `iso3` ="CZE",  `title_post_sort` ="CZECHIA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="CZ";
UPDATE orm_country SET  `iso3` ="DNK",  `title_post_sort` ="DENMARK",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="DK";
UPDATE orm_country SET  `iso3` ="EST",  `title_post_sort` ="ESTONIA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="EE";
UPDATE orm_country SET  `iso3` ="FIN",  `title_post_sort` ="FINLAND",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="FI";
UPDATE orm_country SET  `iso3` ="FRA",  `title_post_sort` ="FRANKREICH",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="FR";
UPDATE orm_country SET  `iso3` ="DEU",  `title_post_sort` ="DEUTSCHLAND",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="DE";
UPDATE orm_country SET  `iso3` ="GRC",  `title_post_sort` ="GREECE",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="GR";
UPDATE orm_country SET  `iso3` ="HUN",  `title_post_sort` ="HUNGARY",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="HU";
UPDATE orm_country SET  `iso3` ="IRL",  `title_post_sort` ="IRELAND",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="IE";
UPDATE orm_country SET  `iso3` ="ITA",  `title_post_sort` ="ITALIEN",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="IT";
UPDATE orm_country SET  `iso3` ="LVA",  `title_post_sort` ="LATVIA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="LV";
UPDATE orm_country SET  `iso3` ="LTU",  `title_post_sort` ="LITHUANIA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="LT";
UPDATE orm_country SET  `iso3` ="LUX",  `title_post_sort` ="LUXEMBOURG",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="LU";
UPDATE orm_country SET  `iso3` ="MLT",  `title_post_sort` ="MALTA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="MT";
UPDATE orm_country SET  `iso3` ="NLD",  `title_post_sort` ="NETHERLANDS",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="NL";
UPDATE orm_country SET  `iso3` ="POL",  `title_post_sort` ="POLAND",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="PL";
UPDATE orm_country SET  `iso3` ="PRT",  `title_post_sort` ="PORTUGAL",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="PT";
UPDATE orm_country SET  `iso3` ="ROU",  `title_post_sort` ="ROMANIA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="RO";
UPDATE orm_country SET  `iso3` ="SVK",  `title_post_sort` ="SLOVAKIA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="SK";
UPDATE orm_country SET  `iso3` ="SVN",  `title_post_sort` ="SLOVENIA",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="SI";
UPDATE orm_country SET  `iso3` ="ESP",  `title_post_sort` ="SPAIN",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="ES";
UPDATE orm_country SET  `iso3` ="SWE",  `title_post_sort` ="SWEDEN",  `updated_at` ="2023-06-06 09:38:10" WHERE  `iso2` ="SE";
